create table students(userid varchar(40) not null primary key,emailid varchar(50) not null, password varchar(30) not null,name varchar(30) not null,gender varchar(6) not null,fname varchar(30) not null,foccupation varchar(30) not null, mname varchar(30) not null,dob varchar(30) not null,pic varchar(30),presentadsress varchar(100) not null,permaddress varchar(100) not null,smobno varchar(10) not null,fmobno varchar(10) not null,tnoe varchar(30) not null,tyop varchar(30) not null,tboard varchar(30) not null,tsname varchar(30) not null,tmos varchar(30) not null,tsper varchar(30) not null,tactper varchar(30) not null,twnoe varchar(30),twyop varchar(30),twboard varchar(30),twsname varchar(30),twmos varchar(30),twsper varchar(30),twactper varchar(30),dnou varchar(30),stream varchar(30),dyop varchar(30),dsper varchar(30),uregno varchar(30),urollno varchar(30),cursem varchar(2) not null,marks1 varchar(6),marks2 varchar(6),marks3 varchar(6),marks4 varchar(6),marks5 varchar(6),marks6 varchar(6),marks7 varchar(6),marks8 varchar(6));
ALTER TABLE documents CHANGE subject subject varchar(60) DEFAULT NULL;
create table coordinators(name varchar(30) not null, email varchar(30) not null,mobno varchar(30) not null,userid varchar(30) primary key,password varchar(30) not null);
create table documents(name varchar(30) not null primary key, subject varchar(30) not null,date varchar(15));
create table teachers(name varchar(30) not null, email varchar(30) not null,mobno varchar(30) not null,userid varchar(30) primary key,password varchar(30) not null);
create table hods(name varchar(30) not null, email varchar(30) not null,mobno varchar(30) not null,userid varchar(30) primary key,password varchar(30) not null);
create table notices(name varchar(30) not null primary key, subject varchar(30) not null,date varchar(15));
ALTER table tdocs change date date varchar(30) not null;
ALTER table students change aoi aoi varchar(150) default null;
create table tattendance(name varchar(30) not null primary key, subject varchar(30) not null,date varchar(15));
create table tnotices(name varchar(30) not null primary key, subject varchar(30) not null,date varchar(15));
create table tdocs(name varchar(30) not null primary key, subject varchar(30) not null,date varchar(15));
ALTER table tdocs add column location varchar(150) default null;
create table cnotices(name varchar(30) not null primary key, subject varchar(30) not null,date varchar(30),location varchar(150) default null);
ALTER table vfnotes change name name varchar(100) not null;
ALTER table students add column flocation varchar(50) default null;
create table semmarksheet(name varchar(30) not null primary key,date varchar(30),location varchar(150),sem varchar(2),userid varchar(40),FOREIGN KEY(userid) REFERENCES students(userid));
create table vfnotices(name varchar(30) not null primary key, subject varchar(30) not null,date varchar(30),location varchar(150) default null);
create table vfattendance(name varchar(30) not null primary key, subject varchar(30) not null,date varchar(30),location varchar(150) default null);
create table vfnotes(name varchar(30) not null primary key, subject varchar(30) not null,date varchar(30),location varchar(150) default null);
create table vfaculty(name varchar(30) not null, email varchar(30) not null,mobno varchar(30) not null,userid varchar(30) primary key,password varchar(30) not null);
create table questionpaper(name varchar(150) not null primary key, subject varchar(150) not null,date varchar(50),location varchar(200) default null,userid varchar(50),FOREIGN KEY(userid) REFERENCES students(userid));
